GEMMA4_26B_A4B_JSON = """
{
  "architectures": [
    "Gemma4ForConditionalGeneration"
  ],
  "audio_config": null,
  "audio_ms_per_token": 40,
  "audio_token_id": 258881,
  "boa_token_id": 256000,
  "boi_token_id": 255999,
  "dtype": "bfloat16",
  "eoa_token_id": 258883,
  "eoi_token_id": 258882,
  "image_token_id": 258880,
  "initializer_range": 0.02,
  "model_type": "gemma4",
  "text_config": {
    "_sliding_window_pattern": 6,
    "attention_bias": false,
    "attention_dropout": 0.0,
    "attention_k_eq_v": true,
    "attention_use_bidirectional": "vision",
    "attn_logit_softcapping": null,
    "bos_token_id": 2,
    "dtype": "bfloat16",
    "enable_moe_block": true,
    "eos_token_id": 1,
    "expert_intermediate_size": 704,
    "final_logit_softcapping": 30.0,
    "global_head_dim": 512,
    "head_dim": 256,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 2816,
    "hidden_size_per_layer_input": null,
    "initializer_range": 0.02,
    "intermediate_size": 2112,
    "layer_types": [
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gemma4_text",
    "num_attention_heads": 16,
    "num_experts": 128,
    "num_global_key_value_heads": 2,
    "num_hidden_layers": 30,
    "num_key_value_heads": 8,
    "num_kv_shared_layers": 0,
    "pad_token_id": 0,
    "query_pre_attn_scalar": 256,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "partial_rotary_factor": 0.25,
        "rope_theta": 1000000.0,
        "rope_type": "proportional"
      },
      "sliding_attention": {
        "rope_theta": 10000.0,
        "rope_type": "default"
      }
    },
    "routed_layer_pattern": [],
    "sliding_window": 1024,
    "stream_and_decode_in_f32": true,
    "tie_word_embeddings": true,
    "top_k_experts": 8,
    "use_bidirectional_attention": null,
    "use_cache": true,
    "use_double_wide_mlp": false,
    "vocab_size": 262144,
    "vocab_size_per_layer_input": 262144
  },
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0.dev0",
  "vision_config": {
    "attention_bias": false,
    "attention_dropout": 0.0,
    "default_output_length": 280,
    "dtype": "bfloat16",
    "global_head_dim": 72,
    "head_dim": 72,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 1152,
    "intermediate_size": 4304,
    "layer_types": [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "",
    "num_attention_heads": 16,
    "num_hidden_layers": 27,
    "num_key_value_heads": 16,
    "patch_size": 16,
    "pooling_kernel_size": 3,
    "position_embedding_size": 10240,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "rope_theta": 100.0,
        "rope_type": "default"
      }
    },
    "use_bidirectional_attention": "vision",
    "use_clipped_linears": false
  },
  "vision_soft_tokens_per_image": 280
}
"""

GEMMA4_31B_JSON = """
{
  "architectures": [
    "Gemma4ForConditionalGeneration"
  ],
  "audio_config": null,
  "audio_ms_per_token": 40,
  "audio_soft_tokens_per_image": 750,
  "audio_token_id": 258881,
  "boa_token_id": 256000,
  "boi_token_id": 255999,
  "dtype": "bfloat16",
  "eoa_token_id": 258883,
  "eoi_token_id": 258882,
  "eos_token_id": [
    1,
    106
  ],
  "image_token_id": 258880,
  "initializer_range": 0.02,
  "model_type": "gemma4",
  "text_config": {
    "_sliding_window_pattern": 6,
    "attention_bias": false,
    "attention_dropout": 0.0,
    "attention_k_eq_v": true,
    "attention_use_bidirectional": "vision",
    "attn_logit_softcapping": null,
    "bos_token_id": 2,
    "dtype": "bfloat16",
    "enable_moe_block": false,
    "eos_token_id": 1,
    "expert_intermediate_size": null,
    "final_logit_softcapping": 30.0,
    "global_head_dim": 512,
    "head_dim": 256,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 5376,
    "hidden_size_per_layer_input": null,
    "initializer_range": 0.02,
    "intermediate_size": 21504,
    "layer_types": [
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gemma4_text",
    "num_attention_heads": 32,
    "num_experts": null,
    "num_global_key_value_heads": 4,
    "num_hidden_layers": 60,
    "num_key_value_heads": 16,
    "num_kv_shared_layers": 0,
    "pad_token_id": 0,
    "query_pre_attn_scalar": 256,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "partial_rotary_factor": 0.25,
        "rope_theta": 1000000.0,
        "rope_type": "proportional"
      },
      "sliding_attention": {
        "rope_theta": 10000.0,
        "rope_type": "default"
      }
    },
    "routed_layer_pattern": null,
    "sliding_window": 1024,
    "stream_and_decode_in_f32": false,
    "tie_word_embeddings": true,
    "top_k_experts": null,
    "use_bidirectional_attention": null,
    "use_cache": true,
    "use_double_wide_mlp": false,
    "vocab_size": 262144,
    "vocab_size_per_layer_input": 262144
  },
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0.dev0",
  "vision_config": {
    "attention_bias": false,
    "attention_dropout": 0.0,
    "default_output_length": 280,
    "dtype": "bfloat16",
    "global_head_dim": 72,
    "head_dim": 72,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 1152,
    "intermediate_size": 4304,
    "layer_types": [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "",
    "num_attention_heads": 16,
    "num_hidden_layers": 27,
    "num_key_value_heads": 16,
    "patch_size": 16,
    "pooling_kernel_size": 3,
    "position_embedding_size": 10240,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "rope_theta": 100.0,
        "rope_type": "default"
      }
    },
    "use_bidirectional_attention": "vision",
    "use_clipped_linears": false,
    "vocab_offset": 262144,
    "vocab_size": 128
  },
  "vision_soft_tokens_per_image": 280
}
"""


GEMMA4_E4B_JSON = """
{
  "architectures": [
    "Gemma4ForConditionalGeneration"
  ],
  "audio_config": {
    "_name_or_path": "",
    "architectures": null,
    "chunk_size_feed_forward": 0,
    "conf_attention_chunk_size": 12,
    "conf_attention_context_left": 13,
    "conf_attention_context_right": 0,
    "conf_attention_invalid_logits_value": -1000000000.0,
    "conf_attention_logit_cap": 50.0,
    "conf_conv_kernel_size": 5,
    "conf_hidden_size": 1024,
    "conf_num_attention_heads": 8,
    "conf_num_hidden_layers": 12,
    "conf_positional_bias_size": 1024,
    "conf_reduction_factor": 1,
    "conf_residual_weight": 0.5,
    "dtype": "bfloat16",
    "embedding_norm_eps": 1e-06,
    "gradient_clipping": 10000000000.0,
    "hidden_size": 1024,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "input_feat_size": 128,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "model_type": "gemma4_audio",
    "output_attentions": false,
    "output_hidden_states": false,
    "output_proj_dims": 1536,
    "problem_type": null,
    "return_dict": true,
    "rms_norm_eps": 1e-06,
    "sscp_conv_channel_size": [
      128,
      32
    ],
    "sscp_conv_eps": 1e-06,
    "sscp_conv_group_norm_eps": 1e-06,
    "sscp_conv_kernel_size": [
      [
        3,
        3
      ],
      [
        3,
        3
      ]
    ],
    "sscp_conv_norm_type": "layer_norm",
    "sscp_conv_padding_type": "semicausal",
    "sscp_conv_stride_size": [
      [
        2,
        2
      ],
      [
        2,
        2
      ]
    ],
    "sscp_conv_time_pad_bottom": null,
    "sscp_conv_time_pad_top": null,
    "streaming": false,
    "streaming_chunk_size": 51,
    "streaming_stride": 48,
    "use_clipped_linears": true,
    "vocab_offset": 262272,
    "vocab_size": 128
  },
  "audio_ms_per_token": 40,
  "audio_soft_tokens_per_image": 750,
  "audio_token_id": 258881,
  "boa_token_id": 256000,
  "boi_token_id": 255999,
  "dtype": "bfloat16",
  "eoa_token_id": 258883,
  "eoi_token_id": 258882,
  "eos_token_id": [
    1,
    106
  ],
  "image_token_id": 258880,
  "initializer_range": 0.02,
  "model_type": "gemma4",
  "text_config": {
    "_sliding_window_pattern": 6,
    "attention_bias": false,
    "attention_dropout": 0.0,
    "attention_k_eq_v": false,
    "attention_use_bidirectional": null,
    "attn_logit_softcapping": null,
    "bos_token_id": 2,
    "dtype": "bfloat16",
    "enable_moe_block": false,
    "eos_token_id": 1,
    "expert_intermediate_size": null,
    "final_logit_softcapping": 30.0,
    "global_head_dim": 512,
    "head_dim": 256,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 2560,
    "hidden_size_per_layer_input": 256,
    "initializer_range": 0.02,
    "intermediate_size": 10240,
    "layer_types": [
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gemma4_text",
    "num_attention_heads": 8,
    "num_experts": null,
    "num_global_key_value_heads": null,
    "num_hidden_layers": 42,
    "num_key_value_heads": 2,
    "num_kv_shared_layers": 18,
    "pad_token_id": 0,
    "query_pre_attn_scalar": 256,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "partial_rotary_factor": 0.25,
        "rope_theta": 1000000.0,
        "rope_type": "proportional"
      },
      "sliding_attention": {
        "rope_theta": 10000.0,
        "rope_type": "default"
      }
    },
    "routed_layer_pattern": null,
    "sliding_window": 512,
    "stream_and_decode_in_f32": false,
    "tie_word_embeddings": true,
    "top_k_experts": null,
    "use_bidirectional_attention": null,
    "use_cache": true,
    "use_double_wide_mlp": false,
    "vocab_size": 262144,
    "vocab_size_per_layer_input": 262144
  },
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0.dev0",
  "vision_config": {
    "attention_bias": false,
    "attention_dropout": 0.0,
    "default_output_length": 280,
    "dtype": "bfloat16",
    "global_head_dim": 64,
    "head_dim": 64,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 768,
    "intermediate_size": 3072,
    "layer_types": [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "",
    "num_attention_heads": 12,
    "num_hidden_layers": 16,
    "num_key_value_heads": 12,
    "patch_size": 16,
    "pooling_kernel_size": 3,
    "position_embedding_size": 10240,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "rope_theta": 100.0,
        "rope_type": "default"
      }
    },
    "use_bidirectional_attention": "vision",
    "use_clipped_linears": true,
    "vocab_offset": 262144,
    "vocab_size": 128
  },
  "vision_soft_tokens_per_image": 280
}
"""

GEMMA4_E2B_JSON = """
{
  "architectures": [
    "Gemma4ForConditionalGeneration"
  ],
  "audio_config": {
    "_name_or_path": "",
    "architectures": null,
    "chunk_size_feed_forward": 0,
    "conf_attention_chunk_size": 12,
    "conf_attention_context_left": 13,
    "conf_attention_context_right": 0,
    "conf_attention_invalid_logits_value": -1000000000.0,
    "conf_attention_logit_cap": 50.0,
    "conf_conv_kernel_size": 5,
    "conf_hidden_size": 1024,
    "conf_num_attention_heads": 8,
    "conf_num_hidden_layers": 12,
    "conf_positional_bias_size": 1024,
    "conf_reduction_factor": 1,
    "conf_residual_weight": 0.5,
    "dtype": "bfloat16",
    "embedding_norm_eps": 1e-06,
    "gradient_clipping": 10000000000.0,
    "hidden_size": 1024,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "input_feat_size": 128,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "model_type": "gemma4_audio",
    "output_attentions": false,
    "output_hidden_states": false,
    "output_proj_dims": 1536,
    "problem_type": null,
    "return_dict": true,
    "rms_norm_eps": 1e-06,
    "sscp_conv_channel_size": [
      128,
      32
    ],
    "sscp_conv_eps": 1e-06,
    "sscp_conv_group_norm_eps": 1e-06,
    "sscp_conv_kernel_size": [
      [
        3,
        3
      ],
      [
        3,
        3
      ]
    ],
    "sscp_conv_norm_type": "layer_norm",
    "sscp_conv_padding_type": "semicausal",
    "sscp_conv_stride_size": [
      [
        2,
        2
      ],
      [
        2,
        2
      ]
    ],
    "sscp_conv_time_pad_bottom": null,
    "sscp_conv_time_pad_top": null,
    "streaming": false,
    "streaming_chunk_size": 51,
    "streaming_stride": 48,
    "use_clipped_linears": true,
    "vocab_offset": 262272,
    "vocab_size": 128
  },
  "audio_ms_per_token": 40,
  "audio_soft_tokens_per_image": 750,
  "audio_token_id": 258881,
  "boa_token_id": 256000,
  "boi_token_id": 255999,
  "dtype": "bfloat16",
  "eoa_token_id": 258883,
  "eoi_token_id": 258882,
  "eos_token_id": [
    1,
    106
  ],
  "image_token_id": 258880,
  "initializer_range": 0.02,
  "model_type": "gemma4",
  "text_config": {
    "_sliding_window_pattern": 5,
    "attention_bias": false,
    "attention_dropout": 0.0,
    "attention_k_eq_v": false,
    "attention_use_bidirectional": null,
    "attn_logit_softcapping": null,
    "bos_token_id": 2,
    "dtype": "bfloat16",
    "enable_moe_block": false,
    "eos_token_id": 1,
    "expert_intermediate_size": null,
    "final_logit_softcapping": 30.0,
    "global_head_dim": 512,
    "head_dim": 256,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 1536,
    "hidden_size_per_layer_input": 256,
    "initializer_range": 0.02,
    "intermediate_size": 6144,
    "layer_types": [
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "sliding_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "gemma4_text",
    "num_attention_heads": 8,
    "num_experts": null,
    "num_global_key_value_heads": null,
    "num_hidden_layers": 35,
    "num_key_value_heads": 1,
    "num_kv_shared_layers": 20,
    "pad_token_id": 0,
    "query_pre_attn_scalar": 256,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "partial_rotary_factor": 0.25,
        "rope_theta": 1000000.0,
        "rope_type": "proportional"
      },
      "sliding_attention": {
        "rope_theta": 10000.0,
        "rope_type": "default"
      }
    },
    "routed_layer_pattern": null,
    "sliding_window": 512,
    "sliding_window_pattern": 5,
    "stream_and_decode_in_f32": false,
    "tie_word_embeddings": true,
    "top_k_experts": null,
    "use_bidirectional_attention": null,
    "use_cache": true,
    "use_double_wide_mlp": true,
    "vocab_size": 262144,
    "vocab_size_per_layer_input": 262144
  },
  "tie_word_embeddings": true,
  "transformers_version": "5.3.0.dev0",
  "vision_config": {
    "attention_bias": false,
    "attention_dropout": 0.0,
    "default_output_length": 280,
    "dtype": "bfloat16",
    "global_head_dim": 64,
    "head_dim": 64,
    "hidden_activation": "gelu_pytorch_tanh",
    "hidden_size": 768,
    "intermediate_size": 3072,
    "layer_types": [
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention",
      "full_attention"
    ],
    "max_position_embeddings": 131072,
    "model_type": "",
    "num_attention_heads": 12,
    "num_hidden_layers": 16,
    "num_key_value_heads": 12,
    "patch_size": 16,
    "pooling_kernel_size": 3,
    "position_embedding_size": 10240,
    "rms_norm_eps": 1e-06,
    "rope_parameters": {
      "full_attention": {
        "rope_theta": 100.0,
        "rope_type": "default"
      }
    },
    "use_bidirectional_attention": "vision",
    "use_clipped_linears": true,
    "vocab_offset": 262144,
    "vocab_size": 128
  },
  "vision_soft_tokens_per_image": 280
}
"""

ALL_CONFIGS = [
  GEMMA4_26B_A4B_JSON, GEMMA4_E2B_JSON, GEMMA4_E4B_JSON, GEMMA4_31B_JSON
]
