#!/usr/bin/env python3
import base64
import gzip
import json
import sys
import textwrap
import threading
import time
from pathlib import Path
from typing import List
from argparse import ArgumentParser

import numpy as np
import requests
from rich.console import Console
from rich.layout import Layout
from rich.live import Live
from rich.panel import Panel
from rich.text import Text

# --- Configuration ---
SERVER_URL = "http://localhost:8081"

def fetch_stream(request_id: int, prompt_text: str):
    """
    Worker function to fetch a single stream from the server in a thread.
    """
    payload = {"id": request_id, "text": prompt_text}
    headers = {"accept": "application/json", "Content-Type": "application/json"}
    global responses, responses_lock, responses_done, SERVER_URL

    try:
        t_first, t_start = None, time.perf_counter()
        with requests.get(
            SERVER_URL + "/stream",
            headers=headers,
            json=payload,
            stream=True,
            timeout=5 * 60,  # 5 minutes
        ) as response:
            response.raise_for_status()
            for i, chunk in enumerate(response.iter_content(chunk_size=None, decode_unicode=True)):
                if i == 0:
                    t_first = time.perf_counter()
                    with open("log.txt", "a") as f:
                        f.write(f"Time to first response: {t_first - t_start:.4e} s\n")
                if chunk:
                    with responses_lock:
                        responses[request_id]["response"] += chunk
            t_stop = time.perf_counter()
            with open("log.txt", "a") as f:
                f.write(f"Decode time: {t_stop - t_first:.4e} s\n")
                f.write(f"Total time: {t_stop - t_start:.4e} s\n")

    except requests.exceptions.RequestException as e:
        with responses_lock:
            responses[request_id]["status"] = f"[bold red]Error: {e}[/]"
    finally:
        with responses_lock:
            if responses[request_id]["status"] == "Running...":
                responses[request_id]["status"] = "[bold green]Done[/]"
            responses_done[request_id] = True


def generate_layout() -> Layout:
    """Creates the Rich Layout for the TUI."""
    layout, panels = Layout(name="root"), []
    panels = []
    HEIGHT, WIDTH = 20, 80
    global responses_lock, responses

    with responses_lock:
        for i, data in responses.items():
            # --- Scrolling/Truncation Logic ---
            full_response_text = data["response"]
            display_text = full_response_text
            new_text = textwrap.wrap(display_text, width=WIDTH - 4)
            new_text = "\n".join(new_text[-(HEIGHT - 2) :])

            # Use Text to prevent re-parsing of Rich markup and handle wrapping
            # response_content = Text(full_response_text, no_wrap=True, overflow="fold")
            response_content = Text(new_text, no_wrap=True, overflow="crop")

            # Determine border style based on status
            border_style = "red" if "Error" in data["status"] else "yellow"
            border_style = "green" if "Done" in data["status"] else border_style

            opts = dict(subtitle_align="left", border_style=border_style, height=HEIGHT, width=WIDTH)
            panels.append(
                Panel(response_content, title=f"Request #{i}", subtitle=f"Prompt: {data['prompt'][:50]}...", **opts)
            )
    layout.split_column(*panels)
    return layout


def profile_issue():
    headers = {"accept": "application/json", "Content-Type": "application/json"}
    global SERVER_URL
    server_url = SERVER_URL + "/profile"
    requests.get(server_url, headers=headers)


def set_generation_length(length: int):
    global SERVER_URL
    headers = {"accept": "application/json", "Content-Type": "application/json"}
    server_url = SERVER_URL + "/set_generation_length"
    requests.get(server_url, headers=headers, params={"length": length})


def retrieve(id: int):
    global SERVER_URL
    headers = {"accept": "application/json", "Content-Type": "application/json"}
    server_url = SERVER_URL + "/retrieve"
    print(requests.get(server_url, headers=headers, params={"id": id}))


def investigate(id: int):
    global SERVER_URL
    headers = {"accept": "application/json", "Content-Type": "application/json"}
    server_url = SERVER_URL + "/investigate"
    requests.get(server_url, headers=headers, params={"id": id})


def main():
    global responses, MAX_PANEL_LINES, responses_lock, responses_done, SERVER_URL
    all_prompts = get_prompts()

    # This controls the "scrolling" effect. It's the max number of lines
    # displayed in a panel. When text exceeds this, only the latest lines are shown.
    MAX_PANEL_LINES = 15
    # ---------------------

    parser = ArgumentParser()
    parser.add_argument("--profile", action="store_true", default=False)
    parser.add_argument("--decode-length", "-d", default=32, type=int)
    parser.add_argument("--query-num", "-q", default=18, type=int)
    parser.add_argument("--port", "-p", default=8081, type=int)

    args = parser.parse_args()
    SERVER_URL = f"http://localhost:{args.port}"
    idxs = np.random.randint(0, len(all_prompts), args.query_num)
    PROMPTS = [all_prompts[idx] for idx in idxs]

    if args.profile:
        profile_issue()
        return

    # A thread-safe dictionary to store the state of each streaming response.
    # The structure will be: { request_id: {"prompt": str, "response": str, "status": str} }
    GLOBAL_ID = time.time_ns() % 2**30
    responses = {
        (GLOBAL_ID + i): {"prompt": prompt, "response": "", "status": "Running..."} for i, prompt in enumerate(PROMPTS)
    }
    responses_done = {k: False for k in responses.keys()}
    responses_lock = threading.Lock()
    console = Console()

    set_generation_length(args.decode_length)
    threads = []
    console.print("[bold cyan]Starting streaming requests... Press Ctrl+C to exit.[/]")
    time.sleep(1)  # Give user time to read the message

    for i, prompt in enumerate(PROMPTS):
        thread = threading.Thread(target=fetch_stream, args=(GLOBAL_ID + i, prompt))
        threads.append(thread)
        thread.start()

    layout = None
    with Live(generate_layout(), screen=True, redirect_stderr=False, transient=True) as live:
        try:
            # This loop now runs indefinitely until the user presses Ctrl+C.
            # It will continue to update the TUI even after all threads are done.
            # while True:
            while not all(v for v in responses_done.values()):
                layout = generate_layout()
                live.update(layout)
                time.sleep(0.1)  # Refresh rate
            with open("log.txt", "a") as f:
                for id, response in responses.items():
                    f.write(f"RESPONSE {id}: ------{response['prompt']}\n")
                    f.write(response["response"])
                    f.write("\n")

            layout = generate_layout()
            live.update(layout)
            time.sleep(0.1)  # Refresh rate
        except KeyboardInterrupt:
            # This block allows for a graceful exit.
            console.print("\n[bold orange3]Exiting gracefully...[/]")

    # Optional: Join threads on exit to ensure clean shutdown, though the program
    # will exit anyway. This is good practice if threads were daemonic.
    for thread in threads:
        thread.join(timeout=0.1)

    with open("log.txt", "a") as f:
        f.write("-" * 80 + "\n")

    console.print("[bold cyan]Application terminated.[/]")
    console.print(layout)


def get_prompts():
    return [
        "Analyze the ethical implications of AI-generated art. Discuss copyright.",
        "Summarize the plot of '1984' by George Orwell concisely.",
        "Explain quantum entanglement for a high school student. Keep it simple.",
        "Describe the characteristics of a healthy forest ecosystem. Mention biodiversity.",
        "Write a haiku about a blooming cherry blossom tree.",
        "Compare and contrast renewable and non-renewable energy sources.",
        "List three major causes of the French Revolution. Be brief.",
        "Define 'epistemology' and provide a simple example of its application.",
        "Imagine a world without internet. How would daily life change?",
        "Discuss the benefits of regular exercise on mental health.",
        "Outline the basic steps of brewing a cup of coffee.",
        "What is blockchain technology? Explain it in layman's terms.",
        "Describe the typical diet of a prehistoric Neanderthal. Be speculative.",
        "Write a short, optimistic sentence about the future of humanity.",
        "Explain the concept of 'net neutrality' and its importance.",
        "List two advantages and two disadvantages of remote work.",
        "Summarize the Socratic method of questioning. Keep it concise.",
        "Describe the feeling of awe when gazing at the night sky.",
        "What is the Turing Test? How does it evaluate AI?",
        "Write a short, humorous sentence about a self-aware toaster.",
        "Explain the difference between weather and climate. Give examples.",
        "List three common cybersecurity threats. How can they be mitigated?",
        "Describe the sound of rain falling on a tin roof.",
        "What are the primary functions of the human liver? Briefly explain.",
        "Imagine a conversation between a dog and a cat. What do they discuss?",
        "Explain the concept of 'opportunity cost' in economics.",
        "List three famous landmarks in Rome. Name their historical significance.",
        "Describe the taste of fresh-baked bread right out of the oven.",
        "What is photosynthesis? Explain its importance to life.",
        "Write a short, inspiring sentence about overcoming adversity.",
        "Explain the difference between a simile and a metaphor.",
        "List three essential tools for a basic woodworking project.",
        "Describe the feeling of sand between your toes at the beach.",
        "What is the scientific method? Outline its core steps.",
        "Imagine a new color. Describe its appearance and emotional impact.",
        "Explain the concept of 'supply and demand' in a market.",
        "List three benefits of learning a new language.",
        "Describe the smell of a pine forest after a summer rain.",
        "What are black holes? Explain their formation briefly.",
        "Write a short, whimsical sentence about a cloud shaped like an animal.",
        "Explain the concept of 'biodiversity hotspots' and their importance.",
        "List three major inventions from the Industrial Revolution.",
        "Describe the sound of wind chimes on a breezy afternoon.",
        "What is natural selection? Explain its role in evolution.",
        "Imagine a city powered entirely by renewable energy. Describe it.",
        "Explain the 'butterfly effect' in chaos theory. Give an example.",
        "List three key features of a well-written short story.",
        "Describe the feeling of excitement before a big adventure.",
        "What is the difference between a virus and bacteria?",
        "Write a short, thought-provoking question about the nature of reality.",
        "Explain the concept of 'cognitive bias.' Provide an example.",
        "List three common ingredients in traditional Italian pasta sauce.",
        "Describe the view from the top of a very tall mountain.",
        "What is the internet of things (IoT)? Give a simple example.",
        "Imagine a world where dreams are shared. How would society change?",
        "Explain the 'tragedy of the commons' in environmental science.",
        "List three benefits of reading fiction regularly.",
        "Describe the smell of freshly cut grass on a summer day.",
        "What is artificial intelligence (AI)? Briefly explain its goals.",
        "Write a short, funny sentence about a talking squirrel.",
        "Explain the difference between a fact and an opinion.",
        "List three different types of clouds and their typical weather.",
        "Describe the feeling of warmth from a crackling fireplace.",
        "What is climate change? List two of its major impacts.",
        "Imagine a new musical instrument. Describe its sound and appearance.",
        "Explain the concept of 'confirmation bias' and its dangers.",
        "List three important figures from ancient Greek philosophy.",
        "Describe the sound of waves crashing gently on a sandy shore.",
        "What is a supernova? Briefly explain its significance.",
        "Write a short, inspiring sentence about the power of knowledge.",
        "Explain the difference between a planet and a dwarf planet.",
        "List three common symptoms of a cold or flu.",
        "Describe the taste of a ripe, juicy strawberry.",
        "What is cryptography? Explain its basic purpose.",
        "Imagine a day when gravity briefly disappears. What happens?",
        "Explain the concept of 'digital footprint' and its implications.",
        "List three advantages of living in a small town.",
        "Describe the smell of freshly brewed coffee on a cold morning.",
        "What is a galaxy? Briefly describe its components.",
        "Write a short, whimsical sentence about a mischievous elf.",
        "Explain the difference between 'weather' and 'climate' in simple terms.",
        "List three common types of trees found in temperate forests.",
        "Describe the feeling of peacefulness in a quiet library.",
        "What is the ozone layer? Why is it important?",
        "Imagine a machine that translates animal thoughts into human language.",
        "Explain the concept of 'sustainable development.' Give an example.",
        "List three benefits of volunteering in your community.",
        "Describe the sound of a distant train whistle at night.",
        "What is DNA? Briefly explain its function.",
        "Write a short, humorous sentence about a clumsy robot.",
        "Explain the difference between a democratic and autocratic government.",
        "List three healthy food choices for a balanced breakfast.",
        "Describe the smell of rain on hot pavement.",
        "What is a neuron? Briefly explain its role.",
        "Imagine a device that allows you to instantly learn any skill.",
        "Explain the concept of 'cultural relativism' concisely.",
        "List three major rivers in the world and their continents.",
        "Describe the feeling of cool water on a hot day.",
        "What is quantum computing? Explain it simply.",
        "Write a short, optimistic sentence about technological progress.",
        "Explain the difference between a hypothesis and a theory.",
        "List three benefits of meditation for mental well-being.",
        "Describe the sound of birds chirping at dawn.",
        "What is the Big Bang theory? Explain its core idea.",
        "Imagine a plant that glows in the dark. Describe its appearance.",
        "Explain the concept of 'echo chambers' in online communities.",
        "List three famous explorers and their discoveries.",
        "Describe the taste of dark chocolate melting in your mouth.",
        "What is a volcano? Briefly explain its eruption process.",
        "Write a short, inspiring sentence about embracing change.",
        "Explain the difference between empathy and sympathy.",
        "List three common ingredients in a classic Margherita pizza.",
        "Describe the feeling of soft grass under bare feet.",
        "What is the human microbiome? Briefly explain its importance.",
        "Imagine a world where everyone can fly. How does society adapt?",
        "Explain the concept of 'confirmation bias' with an example.",
        "List three major events in the American Civil War.",
        "Describe the sound of laughter echoing through a room.",
        "What is gravity? Briefly explain its effect.",
        "Write a short, whimsical sentence about a talking teapot.",
        "Explain the difference between 'data' and 'information.'",
        "List three common symptoms of a common cold.",
        "Describe the smell of freshly baked bread. Delicious!",
        "What is a satellite? Briefly explain its purpose.",
        "Imagine a personal AI assistant with a sense of humor.",
        "Explain the 'Pareto principle' (80/20 rule) simply.",
        "List three benefits of regular physical activity.",
        "Describe the feeling of warmth from a cozy blanket.",
        "What is virtual reality (VR)? Give an example.",
        "Write a short, inspiring sentence about perseverance.",
        "Explain the difference between 'fact' and 'opinion' clearly.",
        "List three major types of renewable energy.",
        "Describe the sound of ocean waves gently crashing.",
        "What is a black hole? Explain its basic nature.",
        "Imagine a tree that grows money. What would happen?",
        "Explain the concept of 'cognitive dissonance' with an example.",
        "List three benefits of mindful eating.",
        "Describe the smell of rain on a hot summer night.",
        "What is the Internet of Things? Give a simple example.",
        "Write a short, funny sentence about a robot failing.",
        "Explain the difference between 'argument' and 'debate.'",
        "List three common spices used in Indian cuisine.",
        "Describe the taste of a crisp, green apple.",
        "What is a galaxy? Briefly describe its components.",
        "Imagine a world without money. How would transactions occur?",
        "Explain the concept of 'herd immunity' simply.",
        "List three famous landmarks in Paris.",
        "Describe the sound of crickets chirping on a summer evening.",
        "What is a neuron? Explain its basic function.",
        "Write a short, optimistic sentence about human ingenuity.",
        "Explain the difference between 'privacy' and 'security.'",
        "List three benefits of learning to play a musical instrument.",
        "Describe the feeling of soft fur on a friendly pet.",
        "What is a fossil? Briefly explain its formation.",
        "Imagine a portal that leads to any past time period.",
        "Explain the concept of 'supply chain' concisely.",
        "List three common types of clouds.",
        "Describe the smell of freshly cut grass.",
        "What is climate change? List two causes.",
        "Write a short, inspiring sentence about embracing challenges.",
        "Explain the difference between 'equity' and 'equality.'",
        "List three major historical events in the 20th century.",
        "Describe the sound of children laughing joyfully.",
        "What is photosynthesis? Briefly explain its importance.",
        "Imagine a pet that can talk. What would it say?",
        "Explain the 'halo effect' in social psychology.",
        "List three benefits of getting enough sleep.",
        "Describe the taste of sweet, ripe mango.",
        "What is DNA? Explain its primary role.",
        "Write a short, whimsical sentence about a flying pig.",
        "Explain the difference between a 'virus' and a 'worm.'",
        "List three common ingredients in a Caesar salad.",
        "Describe the feeling of cold snow on your skin.",
        "What is the Big Bang theory? Briefly explain it.",
        "Imagine a robot designed for companionship. Describe it.",
        "Explain the concept of 'confirmation bias' simply.",
        "List three major world religions.",
        "Describe the sound of gentle waves on a lake.",
        "What is a black hole? Explain its basic properties.",
        "Write a short, optimistic sentence about space exploration.",
        "Explain the difference between 'qualitative' and 'quantitative' data.",
        "List three benefits of spending time in nature.",
        "Describe the smell of pine needles in a forest.",
        "What is artificial intelligence? Briefly define it.",
        "Imagine a device that lets you visit your own dreams.",
        "Explain the 'Dunning-Kruger effect' with an example.",
        "List three essential items for a hiking trip.",
        "Describe the taste of bitter dark coffee.",
        "What is blockchain technology? Explain its core principle.",
        "Write a short, funny sentence about a clumsy wizard.",
        "Explain the difference between 'responsibility' and 'accountability.'",
        "List three common uses of renewable energy.",
        "Describe the sound of a babbling brook.",
        "What is the atmosphere? Briefly explain its layers.",
        "Imagine a world without borders. How would it function?",
        "Explain the concept of 'cognitive load' simply.",
        "List three major components of a healthy diet.",
        "Describe the feeling of warm sunshine on your face.",
        "What is photosynthesis? Explain its main purpose.",
        "Write a short, inspiring sentence about collective action.",
        "Explain the difference between 'anarchy' and 'democracy.'",
        "List three famous landmarks in New York City.",
        "Describe the sound of sizzling bacon.",
        "What is a galaxy? Briefly describe its formation.",
        "Imagine a plant that can communicate. What would it say?",
        "Explain the 'observer effect' in quantum physics (simplified).",
        "List three benefits of learning basic first aid.",
        "Describe the smell of cinnamon rolls baking.",
        "What is the ozone layer? Briefly explain its function.",
        "Write a short, whimsical sentence about a talking hat.",
        "Explain the difference between 'data mining' and 'machine learning.'",
        "List three common types of exercise.",
        "Describe the feeling of cool silk on your skin.",
        "What is gravity? Briefly explain its discovery.",
        "Imagine a book that changes its story based on your mood.",
        "Explain the concept of 'gamification' with an example.",
        "List three major innovations of the Renaissance.",
        "Describe the sound of rain tapping on a window.",
        "What is a neuron? Explain its basic communication.",
        "Write a short, optimistic sentence about peace.",
        "Explain the difference between 'capitalism' and 'socialism.'",
        "List three common materials used in construction.",
        "Describe the taste of a sour lemon.",
        "What is the Internet? Briefly explain its origins.",
        "Imagine a world where colors have sounds. Describe a symphony.",
        "Explain the 'butterfly effect' in daily life examples.",
        "List three benefits of being a good listener.",
        "Describe the smell of a campfire in the woods.",
        "What is a volcano? Explain its dangers briefly.",
        "Write a short, funny sentence about a dog driving.",
        "Explain the difference between 'prejudice' and 'discrimination.'",
        "List three major events of World War II.",
        "Describe the sound of wind rustling through leaves.",
        "What is DNA? Briefly explain its structure.",
        "Imagine a future where robots do all housework.",
        "Explain the concept of 'confirmation bias' in media.",
        "List three benefits of daily journaling.",
        "Describe the taste of sweet, creamy ice cream.",
        "What is AI? Briefly define its subfields.",
        "Write a short, inspiring sentence about embracing failure.",
        "Explain the difference between 'gross' and 'net' income.",
        "List three common types of human emotions.",
        "Describe the feeling of walking barefoot on dewy grass.",
        "What is a satellite? Explain its orbital mechanics simply.",
        "Imagine a device that records and plays back smells.",
        "Explain the 'fundamental attribution error' simply.",
        "List three major characteristics of a desert ecosystem.",
        "Describe the sound of church bells ringing.",
        "What is the Big Bang theory? Explain its evidence.",
        "Write a short, whimsical sentence about a dragon librarian.",
        "Explain the difference between 'ethics' and 'morality.'",
        "List three benefits of learning to code.",
        "Describe the smell of baking cookies.",
        "What is climate change? List its main human causes.",
        "Imagine a world where plants can move. What happens?",
        "Explain the concept of 'cognitive load' in learning.",
        "List three essential tools for a gardener.",
        "Describe the taste of a juicy, grilled steak.",
        "What is photosynthesis? Briefly explain its chemical process.",
        "Write a short, optimistic sentence about global cooperation.",
        "Explain the difference between 'data privacy' and 'data security.'",
        "List three common types of birds in your region.",
        "Describe the feeling of deep relaxation after a long day.",
        "What is a black hole? Explain its event horizon.",
        "Imagine a pet rock that responds to your thoughts.",
        "Explain the 'Pareto principle' in time management.",
        "List three benefits of practicing gratitude.",
        "Describe the sound of a distant thunderstorm approaching.",
        "What is the Internet of Things? Give a practical example.",
        "Write a short, funny sentence about a shy ghost.",
        "Explain the difference between 'deductive' and 'inductive' reasoning.",
        "List three common spices used in Mexican cuisine.",
        "Describe the taste of fresh, sweet watermelon.",
        "What is a galaxy? Briefly explain different types.",
        "Imagine a world where gravity is optional. How would sports change?",
        "Explain the concept of 'herd mentality' in groups.",
        "List three famous scientists and their contributions.",
        "Describe the sound of a crackling fire on a cold night.",
        "What is a neuron? Explain its parts simply.",
        "Write a short, inspiring sentence about the power of imagination.",
        "Explain the difference between 'conscious' and 'subconscious.'",
        "List three benefits of eating vegetables daily.",
        "Describe the smell of a new book.",
        "What is the ozone layer? Why is it depleting?",
        "Imagine a personal assistant that anticipates your needs.",
        "Explain the 'bystander effect' with a simple example.",
        "List three major challenges facing humanity today.",
        "Describe the taste of a tangy, juicy orange.",
        "What is DNA? Explain its role in heredity.",
        "Write a short, whimsical sentence about a talking fish.",
        "Explain the difference between 'stress' and 'anxiety.'",
        "List three common ingredients in a vegetable stir-fry.",
        "Describe the feeling of warm sand on a sunny beach.",
        "What is the Big Bang theory? Explain its expansion.",
        "Imagine a device that allows you to control your dreams.",
        "Explain the concept of 'confirmation bias' in political views.",
        "List three benefits of mindfulness exercises.",
        "Describe the sound of laughter filling a room.",
        "What is gravity? Briefly explain its influence on tides.",
        "Write a short, optimistic sentence about scientific discovery.",
        "Explain the difference between 'inflation' and 'deflation.'",
        "List three common types of trees in urban areas.",
        "Describe the smell of freshly brewed coffee beans.",
        "What is artificial intelligence? Give a real-world example.",
        "Imagine a world where emotions are visible colors.",
        "Explain the 'Dunning-Kruger effect' in everyday skills.",
        "List three essential items for a picnic.",
        "Describe the taste of a freshly baked cookie.",
        "What is blockchain technology? Explain its security.",
        "Write a short, funny sentence about a confused alien.",
        "Explain the difference between 'theory' and 'law' in science.",
        "List three common uses of solar energy.",
        "Describe the sound of a distant ambulance siren.",
        "What is the atmosphere? Briefly explain its composition.",
        "Imagine a society where kindness is currency.",
        "Explain the concept of 'cognitive bias' in decision-making.",
        "List three major challenges of space travel.",
        "Describe the feeling of fresh air after a storm.",
        "What is photosynthesis? Explain its byproduct.",
        "Write a short, inspiring sentence about courage.",
        "Explain the difference between 'democracy' and 'republic.'",
        "List three famous structures from ancient Egypt.",
        "Describe the sound of ocean waves during a storm.",
        "What is a black hole? Explain its singularity.",
        "Imagine a pet that can change its form.",
        "Explain the 'Pareto principle' in customer service.",
        "List three benefits of outdoor activities.",
        "Describe the smell of a damp forest floor.",
        "What is the Internet of Things? Explain its connectivity.",
        "Write a short, whimsical sentence about a unicorn scientist.",
        "Explain the difference between 'objective' and 'subjective.'",
        "List three common types of pollution.",
        "Describe the taste of a hot, savory soup.",
        "What is a galaxy? Briefly explain its life cycle.",
        "Imagine a world where animals can vote.",
        "Explain the concept of 'groupthink' in decision making.",
        "List three famous composers of classical music.",
        "Describe the sound of wind chimes in a gentle breeze.",
        "What is a neuron? Briefly explain its signal transmission.",
        "Write a short, optimistic sentence about human potential.",
        "Explain the difference between 'copyright' and 'trademark.'",
        "List three benefits of learning history.",
        "Describe the feeling of accomplishment after finishing a task.",
        "What is DNA? Explain its code for life.",
        "Imagine a mirror that shows your past lives.",
        "Explain the 'halo effect' in job interviews.",
        "List three major historical figures from the American Revolution.",
        "Describe the sound of leaves crunching underfoot.",
        "What is climate change? List two solutions.",
        "Write a short, funny sentence about a very slow snail.",
        "Explain the difference between 'data encryption' and 'data backup.'",
        "List three common types of vegetables.",
        "Describe the smell of a freshly mown lawn.",
        "What is a satellite? Explain its uses in communication.",
        "Imagine a city built entirely underground.",
        "Explain the 'bystander effect' in emergency situations.",
        "List three benefits of having a positive attitude.",
        "Describe the taste of a warm, gooey brownie.",
        "What is AI? Briefly explain its learning process.",
        "Write a short, inspiring sentence about unity.",
        "Explain the difference between 'analogy' and 'metaphor.'",
        "List three common types of fruits.",
        "Describe the feeling of calm in a quiet forest.",
        "What is the Big Bang theory? Explain its implications.",
        "Imagine a world where thoughts are telepathic.",
        "Explain the concept of 'confirmation bias' in science.",
        "List three benefits of practicing mindfulness daily.",
        "Describe the sound of a distant train passing by.",
        "What is gravity? Briefly explain its effect on space-time.",
        "Write a short, optimistic sentence about the future of education.",
        "Explain the difference between 'explicit' and 'implicit' memory.",
        "List three common forms of transportation.",
        "Describe the smell of a warm, cozy bakery.",
        "What is photosynthesis? Explain its role in ecosystems.",
        "Imagine a pet that changes color with its mood.",
        "Explain the 'Pareto principle' in sales.",
        "List three benefits of critical thinking.",
        "Describe the sound of a busy city street.",
        "What is the Internet of Things? Explain its impact.",
        "Write a short, whimsical sentence about a talking flower.",
        "Explain the difference between 'absolute' and 'relative' poverty.",
        "List three common types of renewable energy sources.",
        "Describe the taste of a refreshing glass of water.",
        "What is a black hole? Explain its event horizon simply.",
        "Imagine a device that allows you to relive memories.",
        "Explain the concept of 'cognitive dissonance' in choices.",
        "List three famous rivers in South America.",
        "Describe the sound of a gentle rainfall.",
        "What is a neuron? Briefly explain its function in the brain.",
        "Write a short, inspiring sentence about overcoming fear.",
        "Explain the difference between 'passion' and 'hobby.'",
        "List three common ingredients in a homemade sandwich.",
        "Describe the feeling of warmth from a sunny window.",
        "What is DNA? Explain its role in evolution.",
        "Imagine a world where animals wear clothes.",
        "Explain the 'halo effect' in consumer behavior.",
        "List three major events of the Cold War.",
        "Describe the sound of leaves rustling in a gentle breeze.",
        "What is climate change? List its environmental impacts.",
        "Write a short, funny sentence about a robot chef.",
        "Explain the difference between 'router' and 'modem.'",
        "List three common types of birds.",
        "Describe the smell of fresh-cut pine wood.",
        "What is a satellite? Explain its use in navigation.",
        "Imagine a house that cleans itself automatically.",
        "Explain the 'bystander effect' in a workplace setting.",
        "List three benefits of practicing gratitude daily.",
        "Describe the taste of sweet, juicy berries.",
        "What is AI? Briefly explain its impact on jobs.",
        "Write a short, optimistic sentence about innovation.",
        "Explain the difference between 'simile' and 'analogy' concisely.",
        "List three common types of desserts.",
        "Describe the feeling of a cool breeze on a hot day.",
        "What is the Big Bang theory? Explain its core idea simply.",
        "Imagine a device that can read minds. What happens?",
        "Explain the concept of 'confirmation bias' in social media.",
        "List three benefits of learning a new skill.",
        "Describe the sound of wind whistling through trees.",
        "What is gravity? Briefly explain its role in planetary orbits.",
        "Write a short, whimsical sentence about a playful cloud.",
        "Explain the difference between 'qualitative' and 'quantitative' research.",
        "List three common types of rocks.",
        "Describe the smell of fresh coffee brewing.",
        "What is photosynthesis? Explain its significance to plants.",
        "Imagine a world where plants can sing.",
        "Explain the 'Pareto principle' in personal finance.",
        "List three benefits of engaging in creative activities.",
        "Describe the sound of a distant waterfall.",
        "What is the Internet of Things? Give a practical application.",
        "Write a short, inspiring sentence about reaching goals.",
        "Explain the difference between 'ethical' and 'legal.'",
        "List three common forms of renewable energy.",
        "Describe the taste of crunchy, salty popcorn.",
        "What is a black hole? Briefly explain its formation process.",
        "Imagine a pet robot that understands emotions.",
        "Explain the concept of 'cognitive dissonance' in beliefs.",
        "List three major mountain ranges in the world.",
        "Describe the sound of soft piano music.",
        "What is a neuron? Explain its role in thought.",
        "Write a short, optimistic sentence about the power of community.",
        "Explain the difference between 'accuracy' and 'precision.'",
        "List three common ingredients in a traditional pizza.",
        "Describe the feeling of warmth from a cozy fireplace.",
        "What is DNA? Briefly explain its double helix.",
        "Imagine a world where animals can build cities.",
        "Explain the 'halo effect' in product marketing.",
        "List three major historical periods.",
        "Describe the sound of footsteps on a wooden floor.",
        "What is climate change? List its economic impacts.",
        "Write a short, funny sentence about a grumpy cat.",
        "Explain the difference between 'phishing' and 'malware.'",
        "List three common types of trees in forests.",
        "Describe the smell of fresh laundry.",
        "What is a satellite? Briefly explain its orbit.",
        "Imagine a world where thoughts are visible.",
        "Explain the 'bystander effect' in everyday life.",
        "List three benefits of spending time alone.",
        "Describe the taste of a hot, crispy french fry.",
        "What is AI? Briefly explain its future potential.",
        "Write a short, inspiring sentence about self-discovery.",
        "Explain the difference between 'explicit' and 'implicit' bias.",
        "List three common types of musical instruments.",
        "Describe the feeling of coolness from a gentle breeze.",
        "What is the Big Bang theory? Explain its cosmic implications.",
        "Imagine a device that makes you invisible.",
        "Explain the concept of 'confirmation bias' in relationships.",
        "List three benefits of practicing gratitude daily.",
        "Describe the sound of a bubbling stream.",
        "What is gravity? Briefly explain its role in galaxies.",
        "Write a short, optimistic sentence about human resilience.",
        "Explain the difference between 'weather' and 'climate' in detail.",
        "List three common types of birds in your neighborhood.",
        "Describe the smell of baking bread from a distance.",
        "What is photosynthesis? Explain its role in the food chain.",
        "Imagine a plant that can cure any disease.",
        "Explain the 'Pareto principle' in project management.",
        "List three benefits of daily exercise.",
        "Describe the sound of a distant, ringing bell.",
        "What is the Internet of Things? Explain its security risks.",
        "Write a short, whimsical sentence about a talking moon.",
        "Explain the difference between 'analogue' and 'digital.'",
        "List three common types of pasta.",
        "Describe the taste of sweet, ripe berries.",
        "What is a black hole? Explain its gravitational pull.",
        "Imagine a pet that can grant wishes.",
        "Explain the concept of 'cognitive dissonance' in consumerism.",
        "List three major deserts in the world.",
        "Describe the sound of laughter echoing through an empty hall.",
        "What is a neuron? Briefly explain its electrical impulses.",
        "Write a short, inspiring sentence about overcoming challenges.",
        "Explain the difference between 'empathy' and 'sympathy' with examples.",
        "List three common ingredients in a basic omelette.",
        "Describe the feeling of relief after a stressful event.",
        "What is DNA? Explain its role in cloning.",
        "Imagine a world where animals can read.",
        "Explain the 'halo effect' in education.",
        "List three major events of the Roman Empire.",
        "Describe the sound of gentle rain falling.",
        "What is climate change? List its social impacts.",
        "Write a short, funny sentence about a cat playing piano.",
        "Explain the difference between 'software' and 'hardware.'",
        "List three common types of fish.",
        "Describe the smell of fresh linen.",
        "What is a satellite? Explain its use in weather forecasting.",
        "Imagine a device that can instantly transport you anywhere.",
        "Explain the 'bystander effect' in online spaces.",
        "List three benefits of having a strong support system.",
        "Describe the taste of a warm, comforting bowl of soup.",
        "What is AI? Briefly explain its ethical considerations.",
        "Write a short, optimistic sentence about future energy.",
        "Explain the difference between 'fact' and 'hypothesis.'",
        "List three common types of cheese.",
        "Describe the feeling of warmth from a sunny window.",
        "What is the Big Bang theory? Briefly explain its origin.",
        "Imagine a world where plants glow in response to music.",
        "Explain the concept of 'confirmation bias' in political discussions.",
        "List three benefits of regular reading.",
        "Describe the sound of a distant church bell.",
        "What is gravity? Briefly explain its impact on stars.",
        "Write a short, whimsical sentence about a dancing teapot.",
        "Explain the difference between 'democracy' and 'autocracy' in detail.",
        "List three common types of forests.",
        "Describe the smell of fresh cut flowers.",
        "What is photosynthesis? Explain its role in oxygen production.",
        "Imagine a pet that can talk to other animals.",
        "Explain the 'Pareto principle' in personal development.",
        "List three benefits of learning new languages.",
        "Describe the sound of a chirping bird outside your window.",
        "What is the Internet of Things? Briefly explain its privacy concerns.",
        "Write a short, inspiring sentence about embracing diversity.",
        "Explain the difference between 'supply' and 'demand' with examples.",
        "List three common types of grains.",
        "Describe the taste of a sweet, ripe peach.",
        "What is a black hole? Explain its effect on light.",
        "Imagine a robot designed for artistic creation.",
        "Explain the concept of 'cognitive dissonance' in political affiliation.",
        "List three major rivers in Asia.",
        "Describe the sound of a gentle flowing river.",
        "What is a neuron? Briefly explain its connections.",
        "Write a short, optimistic sentence about space travel.",
        "Explain the difference between 'efficiency' and 'effectiveness.'",
        "List three common ingredients in a salad.",
        "Describe the feeling of contentment after a good meal.",
        "What is DNA? Explain its role in genetic engineering.",
        "Imagine a world where trees can walk.",
        "Explain the 'halo effect' in personal relationships.",
        "List three major achievements of the space race.",
        "Describe the sound of a distant foghorn.",
        "What is climate change? List its potential solutions.",
        "Write a short, funny sentence about a talking shoe.",
        "Explain the difference between 'cloud computing' and 'local storage.'",
        "List three common types of transportation in cities.",
        "Describe the smell of fresh-baked cookies right out of the oven.",
        "What is a satellite? Briefly explain its role in GPS.",
        "Imagine a building that can reconfigure itself.",
        "Explain the 'bystander effect' in online forums.",
        "List three benefits of learning a musical instrument.",
        "Describe the taste of a warm, sweet waffle.",
        "What is AI? Briefly explain its societal impacts.",
        "Write a short, inspiring sentence about collaboration.",
        "Explain the difference between 'cybersecurity' and 'information security.'",
        "List three common types of fruits in a tropical climate.",
        "Describe the feeling of joy when seeing a loved one.",
        "What is the Big Bang theory? Explain its timeline.",
        "Imagine a device that lets you experience other people's memories.",
        "Explain the concept of 'confirmation bias' in everyday life.",
        "List three benefits of engaging in hobbies.",
        "Describe the sound of a cat purring contentedly.",
        "What is gravity? Briefly explain its influence on tides.",
        "Write a short, whimsical sentence about a mischievous gnome.",
        "Explain the difference between 'weather' and 'climate' in research.",
        "List three common types of insects.",
        "Describe the smell of a fresh rain shower.",
        "What is photosynthesis? Explain its importance to animal life.",
        "Imagine a plant that can clean all pollution.",
        "Explain the 'Pareto principle' in customer satisfaction.",
        "List three benefits of spending time in nature regularly.",
        "Describe the sound of gentle waves on a pebble beach.",
        "What is the Internet of Things? Explain its future implications.",
        "Write a short, inspiring sentence about environmental protection.",
        "Explain the difference between 'qualitative' and 'quantitative' research methods.",
        "List three common types of metals.",
        "Describe the taste of a sweet and tangy raspberry.",
        "What is a black hole? Briefly explain its spaghettification.",
        "Imagine a pet that can change its size.",
        "Explain the concept of 'cognitive dissonance' in moral dilemmas.",
        "List three major volcanoes in the world.",
        "Describe the sound of wind rustling through tall grass.",
        "What is a neuron? Explain its dendrites and axons.",
        "Write a short, optimistic sentence about global peace.",
        "Explain the difference between 'privacy' and 'anonymity.'",
        "List three common ingredients in a basic soup.",
        "Describe the feeling of warmth from a campfire.",
        "What is DNA? Explain its role in cloning simply.",
        "Imagine a world where dreams are prophecies.",
        "Explain the 'halo effect' in brand perception.",
        "List three major events of the Renaissance.",
        "Describe the sound of a distant, echoing laugh.",
        "What is climate change? List its long-term effects.",
        "Write a short, funny sentence about a very smart dog.",
        "Explain the difference between 'virus' and 'worm' concisely.",
        "List three common types of trees in cold climates.",
        "Describe the smell of freshly brewed tea.",
        "What is a satellite? Explain its use in communication clearly.",
        "Imagine a city powered by human thought.",
        "Explain the 'bystander effect' in a public setting.",
        "List three benefits of learning a new language as an adult.",
        "Describe the taste of a hot, crispy pizza crust.",
        "What is AI? Briefly explain its potential societal benefits.",
        "Write a short, inspiring sentence about hope.",
        "Explain the difference between 'empathy' and 'pity.'",
        "List three common types of vegetables in a garden.",
        "Describe the feeling of soft sand between your toes.",
        "What is the Big Bang theory? Explain its implications for matter.",
        "Imagine a device that lets you talk to animals.",
        "Explain the concept of 'confirmation bias' in news consumption.",
        "List three benefits of regular exercise on physical health.",
        "Describe the sound of a gentle waterfall in a forest.",
        "What is gravity? Briefly explain its impact on stars.",
        "Write a short, whimsical sentence about a talking tree.",
        "Explain the difference between 'fact' and 'belief.'",
        "List three common types of flowers.",
        "Describe the smell of a pine forest in winter.",
        "What is photosynthesis? Explain its role in carbon cycle.",
        "Imagine a plant that can grow any object.",
        "Explain the 'Pareto principle' in personal productivity.",
        "List three benefits of daily meditation.",
        "Describe the sound of wind chimes on a calm evening.",
        "What is the Internet of Things? Explain its impact on homes.",
        "Write a short, inspiring sentence about sustainability.",
        "Explain the difference between 'ethics' and 'law' concisely.",
        "List three common types of birds in a city.",
        "Describe the taste of sweet, creamy yogurt.",
        "What is a black hole? Briefly explain its powerful gravity.",
        "Imagine a pet robot that teaches you new skills.",
        "Explain the concept of 'cognitive dissonance' in relationships.",
        "List three major seas in the world.",
        "Describe the sound of gentle waves on a lake shore.",
        "What is a neuron? Explain its role in memory.",
        "Write a short, optimistic sentence about the future of medicine.",
        "Explain the difference between 'accuracy' and 'validity' in research.",
        "List three common ingredients in a healthy smoothie.",
        "Describe the feeling of warmth from a hot bath.",
        "What is DNA? Explain its role in evolution simply.",
        "Imagine a world where animals can create art.",
        "Explain the 'halo effect' in social interactions.",
        "List three major events of the industrial revolution.",
        "Describe the sound of gentle rain on a rooftop.",
        "What is climate change? List its impact on biodiversity.",
        "Write a short, funny sentence about a clumsy robot chef.",
        "Explain the difference between 'URL' and 'IP address.'",
        "List three common types of landforms.",
        "Describe the smell of freshly baked bread from a bakery.",
        "What is a satellite? Explain its use in remote sensing.",
        "Imagine a device that can translate any language instantly.",
        "Explain the 'bystander effect' in online gaming.",
        "List three benefits of practicing positive affirmations.",
        "Describe the taste of a juicy, sweet apple.",
        "What is AI? Briefly explain its impact on industries.",
        "Write a short, inspiring sentence about overcoming obstacles.",
        "Explain the difference between 'debt' and 'equity.'",
        "List three common types of natural disasters.",
        "Describe the feeling of softness of a fluffy cloud.",
        "What is the Big Bang theory? Explain its implications for life.",
        "Imagine a world where time travel is possible.",
        "Explain the concept of 'confirmation bias' in scientific research.",
        "List three benefits of daily gratitude journaling.",
        "Describe the sound of wind howling in a storm.",
        "What is gravity? Briefly explain its role in black holes.",
        "Write a short, whimsical sentence about a talking cloud.",
        "Explain the difference between 'weather' and 'climate' in terms of scale.",
        "List three common types of reptiles.",
        "Describe the smell of freshly ground coffee.",
        "What is photosynthesis? Explain its process in plants.",
        "Imagine a plant that can generate electricity.",
        "Explain the 'Pareto principle' in customer service (briefly).",
        "List three benefits of volunteering for a cause.",
        "Describe the sound of ocean waves crashing against rocks.",
        "What is the Internet of Things? Briefly explain its impact on cities.",
        "Write a short, inspiring sentence about unity and progress.",
        "Explain the difference between 'ethical' and 'moral' choices.",
        "List three common types of birds of prey.",
        "Describe the taste of a warm, comforting cup of tea.",
        "What is a black hole? Briefly explain its properties.",
        "Imagine a pet robot that cleans your house.",
        "Explain the concept of 'cognitive dissonance' in voting.",
        "List three major lakes in North America.",
        "Describe the sound of a distant, mournful owl hoot.",
        "What is a neuron? Briefly explain its role in movement.",
        "Write a short, optimistic sentence about human kindness.",
        "Explain the difference between 'supply chain' and 'logistics.'",
        "List three common ingredients in a homemade pizza.",
        "Describe the feeling of exhilaration after achieving a goal.",
        "What is DNA? Explain its role in forensic science.",
        "Imagine a world where trees can talk.",
        "Explain the 'halo effect' in job interviews again.",
        "List three major battles of the American Civil War.",
        "Describe the sound of gentle rain on a forest floor.",
        "What is climate change? List its impact on oceans.",
        "Write a short, funny sentence about a very sleepy cat.",
        "Explain the difference between 'CPU' and 'GPU.'",
        "List three common types of amphibians.",
        "Describe the smell of warm, fresh cookies.",
        "What is a satellite? Briefly explain its use in disaster relief.",
        "Imagine a device that lets you control your dreams.",
        "Explain the 'bystander effect' in online harassment.",
        "List three benefits of learning critical thinking skills.",
        "Describe the taste of sweet, ripe banana.",
        "What is AI? Briefly explain its challenges.",
        "Write a short, inspiring sentence about embracing challenges.",
        "Explain the difference between 'data' and 'information' again.",
        "List three common types of desserts in American cuisine.",
        "Describe the feeling of coolness from an air conditioner.",
        "What is the Big Bang theory? Explain its evidence simply.",
        "Imagine a robot designed for medical assistance.",
        "Explain the concept of 'confirmation bias' in personal beliefs.",
        "List three benefits of engaging in artistic endeavors.",
        "Describe the sound of a distant thunderstorm.",
        "What is gravity? Briefly explain its role in planetary formation.",
        "Write a short, whimsical sentence about a flying dog.",
        "Explain the difference between 'analogy' and 'simile' in rhetoric.",
        "List three common types of fish in freshwater.",
        "Describe the smell of fresh laundry drying outside.",
        "What is photosynthesis? Explain its importance to life concisely.",
        "Imagine a plant that grows diamonds.",
        "Explain the 'Pareto principle' in software development.",
        "List three benefits of self-care practices.",
        "Describe the sound of a distant train horn at night.",
        "What is the Internet of Things? Explain its impact on industries.",
        "Write a short, inspiring sentence about building a better future.",
        "Explain the difference between 'risk' and 'uncertainty.'",
        "List three common types of cereals.",
        "Describe the taste of a crispy, salty potato chip.",
        "What is a black hole? Briefly explain its escape velocity.",
        "Imagine a pet that can teleport.",
        "Explain the concept of 'cognitive dissonance' in political actions.",
        "List three major rivers in Europe.",
        "Describe the sound of gentle classical music.",
        "What is a neuron? Explain its basic communication in a network.",
        "Write a short, optimistic sentence about technological advancements.",
        "Explain the difference between 'privacy policy' and 'terms of service.'",
        "List three common ingredients in a traditional curry.",
        "Describe the feeling of peacefulness in a quiet garden.",
        "What is DNA? Explain its role in genetic diseases.",
        "Imagine a world where animals have human-like intelligence.",
        "Explain the 'halo effect' in customer reviews.",
        "List three major historical figures from the American West.",
        "Describe the sound of rain tapping on a window pane.",
        "What is climate change? List its impact on human health.",
        "Write a short, funny sentence about a talking cat detective.",
        "Explain the difference between 'URL' and 'domain name.'",
        "List three common types of birds that migrate.",
        "Describe the smell of warm, fresh baked pie.",
        "What is a satellite? Briefly explain its function in space.",
        "Imagine a device that lets you fast-forward time.",
        "Explain the 'bystander effect' in online forums, briefly.",
        "List three benefits of practicing gratitude daily.",
        "Describe the taste of a sweet, juicy pear.",
        "What is AI? Briefly explain its role in automation.",
        "Write a short, inspiring sentence about the power of belief.",
        "Explain the difference between 'ethical' and 'legal' implications.",
        "List three common types of flowers that bloom in spring.",
        "Describe the feeling of warmth from a sunny beach.",
        "What is the Big Bang theory? Explain its expansion and cooling.",
        "Imagine a robot designed for artistic creation and expression.",
        "Explain the concept of 'confirmation bias' in political news.",
        "List three benefits of engaging in community service.",
        "Describe the sound of a distant dog barking.",
        "What is gravity? Briefly explain its effect on space and time.",
        "Write a short, whimsical sentence about a magical library.",
        "Explain the difference between 'gross' and 'net' profit.",
        "List three common types of insects found in gardens.",
        "Describe the smell of fresh cut grass on a summer morning.",
        "What is photosynthesis? Explain its role in ecosystems concisely.",
        "Imagine a plant that can talk.",
        "Explain the 'Pareto principle' in customer support.",
        "List three benefits of practicing self-compassion.",
        "Describe the sound of waves gently lapping at the shore.",
        "What is the Internet of Things? Explain its impact on privacy.",
        "Write a short, inspiring sentence about resilience in adversity.",
        "Explain the difference between 'cybersecurity' and 'network security.'",
        "List three common types of fish found in oceans.",
        "Describe the taste of a hot, savory slice of pizza.",
        "What is a black hole? Briefly explain its effect on light.",
        "Imagine a pet that can change its color at will.",
        "Explain the concept of 'cognitive dissonance' in personal choices.",
        "List three major deserts in Africa.",
        "Describe the sound of a gentle lullaby.",
        "What is a neuron? Explain its basic function in the brain.",
        "Write a short, optimistic sentence about the future of humanity.",
        "Explain the difference between 'empathy' and 'sympathy' clearly.",
        "List three common ingredients in a classic sandwich.",
        "Describe the feeling of calm in a quiet, secluded spot.",
        "What is DNA? Explain its role in inheritance briefly.",
        "Imagine a world where animals have super powers.",
        "Explain the 'halo effect' in social perception.",
        "List three major events of the Middle Ages.",
        "Describe the sound of a distant, lonely owl hoot.",
        "What is climate change? List its impact on polar regions.",
        "Write a short, funny sentence about a robot losing its keys.",
        "Explain the difference between 'hard drive' and 'RAM.'",
        "List three common types of vegetables you can grow at home.",
        "Describe the smell of warm, fresh rain on pavement.",
        "What is a satellite? Briefly explain its use in climate monitoring.",
        "Imagine a device that lets you explore other planets.",
        "Explain the 'bystander effect' in online forums, with context.",
        "List three benefits of learning basic cooking skills.",
        "Describe the taste of a crispy, fresh salad.",
        "What is AI? Briefly explain its role in scientific research.",
        "Write a short, inspiring sentence about the power of imagination.",
        "Explain the difference between 'fact' and 'opinion' clearly.",
        "List three common types of nuts.",
        "Describe the feeling of warmth from a cozy sweater.",
        "What is the Big Bang theory? Explain its implications for matter.",
        "Imagine a robot designed for companionship and learning.",
        "Explain the concept of 'confirmation bias' in news consumption.",
        "List three benefits of engaging in artistic endeavors regularly.",
        "Describe the sound of a gentle breeze through tree leaves.",
        "What is gravity? Briefly explain its effect on celestial bodies.",
        "Write a short, whimsical sentence about a talking book.",
        "Explain the difference between 'qualitative' and 'quantitative' data analysis.",
        "List three common types of rocks found in sedimentary layers.",
        "Describe the smell of fresh-baked bread from a bustling bakery.",
        "What is photosynthesis? Explain its significance to all life.",
        "Imagine a plant that can sing, emitting beautiful melodies.",
        "Explain the 'Pareto principle' in personal finance with examples.",
        "List three benefits of self-care and relaxation.",
        "Describe the sound of gentle waves on a sandy beach.",
        "What is the Internet of Things? Explain its impact on health.",
        "Write a short, inspiring sentence about embracing new beginnings.",
        "Explain the difference between 'ethical' and 'moral' decision making.",
        "List three common types of birds that sing beautifully.",
        "Describe the taste of sweet, juicy watermelon on a hot day.",
        "What is a black hole? Briefly explain its event horizon again.",
        "Imagine a pet robot that understands and responds to emotions.",
        "Explain the concept of 'cognitive dissonance' in consumer choices.",
        "List three major mountain ranges in North America.",
        "Describe the sound of distant thunder rumbling.",
        "What is a neuron? Explain its role in sensory perception.",
        "Write a short, optimistic sentence about the future of clean energy.",
        "Explain the difference between 'efficiency' and 'productivity.'",
        "List three common ingredients in a traditional stir-fry.",
        "Describe the feeling of accomplishment after a challenging workout.",
        "What is DNA? Explain its role in genetic engineering simply.",
        "Imagine a world where trees can walk and talk.",
        "Explain the 'halo effect' in job candidate evaluation.",
        "List three major historical figures from the American Civil War.",
        "Describe the sound of gentle rain on a canvas tent.",
        "What is climate change? List its impact on water resources.",
        "Write a short, funny sentence about a very clumsy wizard.",
        "Explain the difference between 'URL' and 'web address.'",
        "List three common types of mammals in your region.",
        "Describe the smell of a warm, inviting fireplace.",
        "What is a satellite? Briefly explain its role in communication networks.",
        "Imagine a device that allows you to control the weather.",
        "Explain the 'bystander effect' in emergency situations, simply.",
        "List three benefits of regular physical activity for health.",
        "Describe the taste of a sweet, tangy orange.",
        "What is AI? Briefly explain its role in autonomous vehicles.",
        "Write a short, inspiring sentence about finding inner strength.",
        "Explain the difference between 'empathy' and 'compassion.'",
        "List three common types of fruits in temperate climates.",
        "Describe the feeling of coolness from a mountain breeze.",
        "What is the Big Bang theory? Explain its core concepts.",
        "Imagine a robot designed for artistic expression.",
        "Explain the concept of 'confirmation bias' in political discussions.",
        "List three benefits of daily mindfulness meditation.",
        "Describe the sound of a distant bird singing at dawn.",
        "What is gravity? Briefly explain its effect on planetary motion.",
        "Write a short, whimsical sentence about a talking shoe.",
        "Explain the difference between 'gross' and 'net' income for taxes.",
        "List three common types of trees in deciduous forests.",
        "Describe the smell of freshly brewed coffee in the morning.",
        "What is photosynthesis? Explain its importance to food production.",
        "Imagine a plant that grows currency.",
        "Explain the 'Pareto principle' in software testing.",
        "List three benefits of practicing gratitude for well-being.",
        "Describe the sound of a distant, gentle wind chimes.",
        "What is the Internet of Things? Explain its smart home applications.",
        "Write a short, inspiring sentence about hope for the future.",
        "Explain the difference between 'ethics' and 'morality' in practice.",
        "List three common types of birds that live near water.",
        "Describe the taste of a warm, comforting bowl of oatmeal.",
        "What is a black hole? Briefly explain its accretion disk.",
        "Imagine a pet robot that can play any musical instrument.",
        "Explain the concept of 'cognitive dissonance' in purchasing decisions.",
        "List three major rivers in Asia and their countries.",
        "Describe the sound of a gentle stream flowing over rocks.",
        "What is a neuron? Explain its role in learning and memory.",
        "Write a short, optimistic sentence about global collaboration.",
        "Explain the difference between 'efficiency' and 'effectiveness' in projects.",
        "List three common ingredients in a classic pasta dish.",
        "Describe the feeling of contentment after a satisfying meal.",
        "What is DNA? Explain its role in genetic counseling.",
        "Imagine a world where animals have a universal language.",
        "Explain the 'halo effect' in celebrity endorsements.",
        "List three major wars in human history.",
        "Describe the sound of gentle rain falling on leaves.",
        "What is climate change? List its impact on ecosystems.",
        "Write a short, funny sentence about a robot that loves disco.",
        "Explain the difference between 'HTTPS' and 'HTTP.'",
        "List three common types of wildflowers.",
        "Describe the smell of freshly cut grass on a summer evening.",
        "What is a satellite? Briefly explain its use in defense.",
        "Imagine a device that allows you to visit alternate realities.",
        "Explain the 'bystander effect' in a school setting.",
        "List three benefits of engaging in creative writing.",
        "Describe the taste of a sweet, juicy pineapple.",
        "What is AI? Briefly explain its impact on creativity.",
        "Write a short, inspiring sentence about the power of kindness.",
        "Explain the difference between 'fact' and 'theory' in science.",
        "List three common types of desserts around the world.",
        "Describe the feeling of cool water on your feet.",
        "What is the Big Bang theory? Explain its expansion of space.",
        "Imagine a robot designed for exploring deep space.",
        "Explain the concept of 'confirmation bias' in scientific discovery.",
        "List three benefits of daily gratitude practice.",
        "Describe the sound of a distant train whistle blowing.",
        "What is gravity? Briefly explain its role in planet formation.",
        "Write a short, whimsical sentence about a talking pillow.",
        "Explain the difference between 'qualitative' and 'quantitative' data collection.",
        "List three common types of metamorphic rocks.",
        "Describe the smell of fresh-baked apple pie.",
        "What is photosynthesis? Explain its byproduct, oxygen.",
        "Imagine a plant that provides infinite energy.",
        "Explain the 'Pareto principle' in personal relationships.",
        "List three benefits of practicing positive self-talk.",
        "Describe the sound of gentle waves lapping on a wooden dock.",
        "What is the Internet of Things? Explain its impact on industry.",
        "Write a short, inspiring sentence about pursuing your dreams.",
        "Explain the difference between 'ethical' and 'legal' boundaries.",
        "List three common types of birds that sing at night.",
        "Describe the taste of warm, creamy mashed potatoes.",
        "What is a black hole? Briefly explain its intense gravity.",
        "Imagine a pet robot that helps with homework.",
        "Explain the concept of 'cognitive dissonance' in health choices.",
        "List three major lakes in Africa.",
        "Describe the sound of a gentle breeze through tall trees.",
        "What is a neuron? Explain its basic function in the nervous system.",
        "Write a short, optimistic sentence about the power of learning.",
        "Explain the difference between 'privacy' and 'confidentiality.'",
        "List three common ingredients in a basic chili.",
        "Describe the feeling of warmth from a sunny winter day.",
        "What is DNA? Explain its role in inherited traits.",
        "Imagine a world where animals build complex structures.",
        "Explain the 'halo effect' in leadership.",
        "List three major historical figures from World War II.",
        "Describe the sound of gentle rain falling on a metal roof.",
        "What is climate change? List its impact on agriculture.",
        "Write a short, funny sentence about a sleepy, talking cloud.",
        "Explain the difference between 'broadband' and 'dial-up.'",
        "List three common types of mammals in cold climates.",
        "Describe the smell of freshly laundered clothes.",
        "What is a satellite? Briefly explain its use in scientific research.",
        "Imagine a device that allows you to communicate with plants.",
        "Explain the 'bystander effect' in online forums, with context.",
        "List three benefits of learning basic coding skills.",
        "Describe the taste of a tangy, sweet grapefruit.",
        "What is AI? Briefly explain its role in healthcare.",
        "Write a short, inspiring sentence about the joy of discovery.",
        "Explain the difference between 'simile' and 'analogy' in detail.",
        "List three common types of pastries.",
        "Describe the feeling of cool water splashing on your face.",
        "What is the Big Bang theory? Explain its implications for energy.",
        "Imagine a robot designed for space exploration and construction.",
        "Explain the concept of 'confirmation bias' in personal decisions.",
        "List three benefits of regular meditation practice.",
        "Describe the sound of a distant owl hooting softly.",
        "What is gravity? Briefly explain its role in stellar evolution.",
        "Write a short, whimsical sentence about a talking telescope.",
        "Explain the difference between 'accuracy' and 'precision' in measurement.",
        "List three common types of sedimentary rocks.",
        "Describe the smell of fresh baked cinnamon rolls.",
        "What is photosynthesis? Explain its light-dependent reactions.",
        "Imagine a plant that can predict the future.",
        "Explain the 'Pareto principle' in time management with examples.",
        "List three benefits of engaging in outdoor recreation.",
        "Describe the sound of ocean waves receding from the shore.",
        "What is the Internet of Things? Explain its impact on transportation.",
        "Write a short, inspiring sentence about environmental stewardship.",
        "Explain the difference between 'ethics' and 'values.'",
        "List three common types of trees found in tropical regions.",
        "Describe the taste of warm, creamy chocolate pudding.",
        "What is a black hole? Briefly explain its formation from stars.",
        "Imagine a pet robot that helps you stay organized.",
        "Explain the concept of 'cognitive dissonance' in societal norms.",
        "List three major rivers in South America and their countries.",
        "Describe the sound of a gentle wind whispering through leaves.",
        "What is a neuron? Explain its role in complex thought.",
        "Write a short, optimistic sentence about human ingenuity.",
        "Explain the difference between 'supply' and 'demand' curves.",
        "List three common ingredients in a classic omelette.",
        "Describe the feeling of peacefulness in a quiet, secluded forest.",
        "What is DNA? Explain its role in biotechnology.",
        "Imagine a world where animals can invent things.",
        "Explain the 'halo effect' in political campaigns.",
        "List three major battles of World War I.",
        "Describe the sound of gentle rain falling on an umbrella.",
        "What is climate change? List its impact on marine life.",
        "Write a short, funny sentence about a robot afraid of dust.",
        "Explain the difference between 'HTTP' and 'HTTPS' simply.",
        "List three common types of amphibians in rainforests.",
        "Describe the smell of fresh baked apple crisp.",
        "What is a satellite? Briefly explain its use in disaster monitoring.",
        "Imagine a device that lets you explore historical events.",
        "Explain the 'bystander effect' in a digital community.",
        "List three benefits of continuous learning.",
        "Describe the taste of a sweet, juicy plum.",
        "What is AI? Briefly explain its role in education.",
        "Write a short, inspiring sentence about the power of unity.",
        "Explain the difference between 'debt' and 'credit.'",
        "List three common types of natural resources.",
        "Describe the feeling of softness of a warm blanket.",
        "What is the Big Bang theory? Explain its earliest moments.",
        "Imagine a robot designed for emergency rescue.",
        "Explain the concept of 'confirmation bias' in legal judgments.",
        "List three benefits of daily exercise for mental health.",
        "Describe the sound of a distant bell tolling.",
        "What is gravity? Briefly explain its role in galaxy clusters.",
        "Write a short, whimsical sentence about a talking flowerpot.",
        "Explain the difference between 'explicit' and 'implicit' memory briefly.",
        "List three common types of musical genres.",
        "Describe the smell of freshly brewed chamomile tea.",
        "What is photosynthesis? Explain its carbon dioxide absorption.",
        "Imagine a plant that can heal wounds instantly.",
        "Explain the 'Pareto principle' in sales performance.",
        "List three benefits of practicing self-awareness.",
        "Describe the sound of gentle waves on a rocky shore.",
        "What is the Internet of Things? Explain its impact on healthcare.",
        "Write a short, inspiring sentence about overcoming adversity.",
        "Explain the difference between 'ethical' and 'moral' reasoning.",
        "List three common types of birds that live in deserts.",
        "Describe the taste of a warm, comforting bowl of soup on a cold day.",
        "What is a black hole? Briefly explain its gravitational lensing.",
        "Imagine a pet robot that helps with cooking.",
        "Explain the concept of 'cognitive dissonance' in personal values.",
        "List three major lakes in Europe.",
        "Describe the sound of a gentle breeze through an open window.",
        "What is a neuron? Explain its role in motor control.",
        "Write a short, optimistic sentence about finding solutions.",
        "Explain the difference between 'supply chain management' and 'logistics.'",
        "List three common ingredients in a basic vegetable soup.",
        "Describe the feeling of excitement before a new journey.",
        "What is DNA? Explain its role in gene therapy.",
        "Imagine a world where animals can design buildings.",
        "Explain the 'halo effect' in classroom settings.",
        "List three major figures from ancient Roman history.",
        "Describe the sound of gentle rain on a tent roof.",
        "What is climate change? List its impact on coastal areas.",
        "Write a short, funny sentence about a robot that loves dancing.",
        "Explain the difference between 'Wi-Fi' and 'Bluetooth.'",
        "List three common types of reptiles in tropical climates.",
        "Describe the smell of warm, freshly baked cookies.",
        "What is a satellite? Briefly explain its use in global positioning.",
        "Imagine a device that allows you to experience other people's dreams.",
        "Explain the 'bystander effect' in online gaming forums.",
        "List three benefits of learning mindfulness techniques.",
        "Describe the taste of a hot, crispy churro.",
        "What is AI? Briefly explain its role in cybersecurity.",
        "Write a short, inspiring sentence about courage and determination.",
        "Explain the difference between 'fact' and 'misinformation.'",
        "List three common types of berries.",
        "Describe the feeling of warmth from a sunny afternoon.",
        "What is the Big Bang theory? Explain its implications for the universe.",
        "Imagine a robot designed for companionship and emotional support.",
        "Explain the concept of 'confirmation bias' in legal cases.",
        "List three benefits of daily gratitude journaling, concisely.",
        "Describe the sound of wind whispering through tall grass.",
        "What is gravity? Briefly explain its role in galaxy formation.",
        "Write a short, whimsical sentence about a mischievous talking cat.",
        "Explain the difference between 'qualitative' and 'quantitative' data analysis in research.",
        "List three common types of igneous rocks.",
        "Describe the smell of fresh, damp earth after rain.",
        "What is photosynthesis? Explain its dependence on sunlight.",
        "Imagine a plant that can communicate telepathically.",
        "Explain the 'Pareto principle' in customer relationships.",
        "List three benefits of spending time in nature for mental health.",
        "Describe the sound of gentle waves on a sandy beach.",
        "What is the Internet of Things? Explain its impact on cities.",
        "Write a short, inspiring sentence about global cooperation and peace.",
        "Explain the difference between 'ethical' and 'moral' dilemmas.",
        "List three common types of birds that live in mountains.",
        "Describe the taste of warm, sweet maple syrup.",
        "What is a black hole? Briefly explain its powerful gravitational pull.",
        "Imagine a pet robot that can play any sport.",
        "Explain the concept of 'cognitive dissonance' in ethical decisions.",
        "List three major deserts in South America.",
        "Describe the sound of a distant, joyful song.",
        "What is a neuron? Explain its role in sensory processing.",
        "Write a short, optimistic sentence about the future of exploration.",
        "Explain the difference between 'privacy' and 'confidentiality' in data.",
        "List three common ingredients in a basic sandwich.",
        "Describe the feeling of peace in a quiet, secluded forest.",
        "What is DNA? Explain its role in genetic engineering processes.",
        "Imagine a world where animals have their own technology.",
        "Explain the 'halo effect' in product branding.",
        "List three major historical figures from the Civil Rights Movement.",
        "Describe the sound of gentle rain on a windowpane.",
        "What is climate change? List its impact on animal habitats.",
        "Write a short, funny sentence about a robot trying to bake.",
        "Explain the difference between 'cloud storage' and 'local storage.'",
        "List three common types of mammals found in forests.",
        "Describe the smell of warm, fresh bread from a bakery.",
        "What is a satellite? Briefly explain its use in environmental monitoring.",
        "Imagine a device that allows you to experience the future.",
        "Explain the 'bystander effect' in online harassment, with nuance.",
        "List three benefits of learning basic programming skills.",
        "Describe the taste of a crisp, refreshing cucumber.",
        "What is AI? Briefly explain its role in art generation.",
        "Write a short, inspiring sentence about finding your purpose.",
        "Explain the difference between 'deductive' and 'inductive' reasoning clearly.",
        "List three common types of musical instruments in an orchestra.",
        "Describe the feeling of lightness after a good laugh.",
        "What is the Big Bang theory? Explain its implications for life's origin.",
        "Imagine a robot designed for creative writing.",
        "Explain the concept of 'confirmation bias' in personal interactions.",
        "List three benefits of engaging in team sports.",
        "Describe the sound of a distant bird singing melodiously.",
        "What is gravity? Briefly explain its effect on planetary orbits.",
        "Write a short, whimsical sentence about a talking chessboard.",
        "Explain the difference between 'accuracy' and 'reliability' in research.",
        "List three common types of metamorphic rocks, briefly.",
        "Describe the smell of fresh soil after rain.",
        "What is photosynthesis? Explain its light-independent reactions.",
        "Imagine a plant that can grow any material.",
        "Explain the 'Pareto principle' in business operations.",
        "List three benefits of practicing self-care consistently.",
        "Describe the sound of gentle waves lapping on a tranquil lake.",
        "What is the Internet of Things? Explain its impact on smart cities.",
        "Write a short, inspiring sentence about embracing positive change.",
        "Explain the difference between 'ethical' and 'legal' obligations.",
        "List three common types of birds that are migratory.",
        "Describe the taste of warm, gooey cheese on pizza.",
        "What is a black hole? Briefly explain its gravitational singularity.",
        "Imagine a pet robot that can teach you languages.",
        "Explain the concept of 'cognitive dissonance' in moral choices.",
        "List three major mountain ranges in Europe.",
        "Describe the sound of distant, echoing laughter.",
        "What is a neuron? Explain its role in decision-making.",
        "Write a short, optimistic sentence about the power of imagination.",
        "Explain the difference between 'supply' and 'demand' in economics.",
        "List three common ingredients in a simple salad dressing.",
        "Describe the feeling of warmth from a gentle embrace.",
        "What is DNA? Explain its role in genetic diseases, briefly.",
        "Imagine a world where animals can build civilizations.",
        "Explain the 'halo effect' in social interactions (briefly).",
        "List three major historical periods of artistic movements.",
        "Describe the sound of gentle rain falling on a forest floor.",
        "What is climate change? List its impact on human migration.",
        "Write a short, funny sentence about a robot trying to dance.",
        "Explain the difference between 'LAN' and 'WAN.'",
        "List three common types of fish in saltwater.",
        "Describe the smell of warm, fresh cinnamon buns.",
        "What is a satellite? Briefly explain its use in reconnaissance.",
        "Imagine a device that lets you explore fictional worlds.",
        "Explain the 'bystander effect' in online communities, with examples.",
        "List three benefits of learning public speaking skills.",
        "Describe the taste of a sweet, ripe mango.",
        "What is AI? Briefly explain its role in scientific discovery.",
        "Write a short, inspiring sentence about the pursuit of knowledge.",
        "Explain the difference between 'fact' and 'assumption.'",
        "List three common types of vegetables that grow underground.",
        "Describe the feeling of cool water flowing over your hands.",
        "What is the Big Bang theory? Explain its cosmic evolution.",
        "Imagine a robot designed for environmental cleanup.",
        "Explain the concept of 'confirmation bias' in political views.",
        "List three benefits of daily journaling for mental clarity.",
        "Describe the sound of wind rustling through dry leaves.",
        "What is gravity? Briefly explain its effect on galaxy formation.",
        "Write a short, whimsical sentence about a talking pencil.",
        "Explain the difference between 'weather' and 'climate' in scientific terms.",
        "List three common types of reptiles found in deserts.",
        "Describe the smell of fresh cut lumber.",
        "What is photosynthesis? Explain its efficiency in different plants.",
        "Imagine a plant that can telekinetically move objects.",
        "Explain the 'Pareto principle' in personal productivity, concisely.",
        "List three benefits of spending time in nature for overall health.",
        "Describe the sound of gentle waves on a pebble beach, peacefully.",
        "What is the Internet of Things? Explain its impact on smart homes.",
        "Write a short, inspiring sentence about the importance of kindness.",
        "Explain the difference between 'ethical' and 'moral' choices in life.",
        "List three common types of birds that live in urban areas.",
        "Describe the taste of warm, comforting apple pie.",
        "What is a black hole? Briefly explain its properties again.",
        "Imagine a pet robot that helps with personal fitness.",
        "Explain the concept of 'cognitive dissonance' in a workplace.",
        "List three major lakes in Asia.",
        "Describe the sound of a distant, happy dog barking.",
        "What is a neuron? Explain its role in emotions.",
        "Write a short, optimistic sentence about overcoming challenges.",
        "Explain the difference between 'supply chain' and 'logistics' in detail.",
        "List three common ingredients in a traditional chicken soup.",
        "Describe the feeling of excitement before an unknown adventure.",
        "What is DNA? Explain its role in gene editing.",
        "Imagine a world where animals can communicate telepathically.",
        "Explain the 'halo effect' in consumer decisions.",
        "List three major battles of the American Revolutionary War.",
        "Describe the sound of gentle rain on a metal roof.",
        "What is climate change? List its impact on weather patterns.",
        "Write a short, funny sentence about a robot trying to sing.",
        "Explain the difference between 'HTML' and 'CSS.'",
        "List three common types of mammals in temperate climates.",
        "Describe the smell of fresh baked bread on a cold day.",
        "What is a satellite? Briefly explain its use in education.",
        "Imagine a device that lets you revisit your past.",
        "Explain the 'bystander effect' in a digital social setting.",
        "List three benefits of practicing self-awareness regularly.",
        "Describe the taste of a hot, crispy donut.",
        "What is AI? Briefly explain its role in gaming.",
        "Write a short, inspiring sentence about perseverance and growth.",
        "Explain the difference between 'assets' and 'liabilities.'",
        "List three common types of grains used in baking.",
        "Describe the feeling of warmth from a cozy fireplace in winter.",
        "What is the Big Bang theory? Explain its implications for the universe's size.",
        "Imagine a robot designed for artistic expression and healing.",
        "Explain the concept of 'confirmation bias' in personal growth.",
        "List three benefits of daily gratitude practice, with details.",
        "Describe the sound of wind whispering through pine trees.",
        "What is gravity? Briefly explain its role in stellar life cycles.",
        "Write a short, whimsical sentence about a talking teacup.",
        "Explain the difference between 'qualitative' and 'quantitative' research design.",
        "List three common types of metamorphic rocks, simply.",
        "Describe the smell of fresh, damp earth after a light rain.",
        "What is photosynthesis? Explain its role in the global carbon cycle.",
        "Imagine a plant that can heal any illness.",
        "Explain the 'Pareto principle' in customer retention.",
        "List three benefits of engaging in outdoor activities consistently.",
        "Describe the sound of gentle waves lapping on a quiet lake.",
        "What is the Internet of Things? Explain its impact on retail.",
        "Write a short, inspiring sentence about community building.",
        "Explain the difference between 'ethical' and 'moral' choices (briefly).",
        "List three common types of birds found in forests.",
        "Describe the taste of warm, comforting chicken noodle soup.",
        "What is a black hole? Briefly explain its event horizon and singularity.",
        "Imagine a pet robot that can play any sport with you.",
        "Explain the concept of 'cognitive dissonance' in political views.",
        "List three major deserts in North America.",
        "Describe the sound of a distant, peaceful choir singing.",
        "What is a neuron? Explain its role in muscle control.",
        "Write a short, optimistic sentence about the power of learning.",
        "Explain the difference between 'supply chain' and 'value chain.'",
        "List three common ingredients in a traditional chili recipe.",
        "Describe the feeling of warmth from a sunny window seat.",
        "What is DNA? Explain its role in ancestry tracing.",
        "Imagine a world where animals can build cities and roads.",
        "Explain the 'halo effect' in political elections.",
        "List three major historical figures from ancient Greek history.",
        "Describe the sound of gentle rain on a tent, calmly.",
        "What is climate change? List its impact on extreme weather events.",
        "Write a short, funny sentence about a robot trying to paint.",
        "Explain the difference between 'HTML' and 'JavaScript.'",
        "List three common types of amphibians in temperate climates.",
        "Describe the smell of fresh baked apple pie, warm and sweet.",
        "What is a satellite? Briefly explain its use in disaster prediction.",
        "Imagine a device that allows you to communicate with animals.",
        "Explain the 'bystander effect' in online emergencies.",
        "List three benefits of learning critical thinking skills (briefly).",
        "Describe the taste of a crispy, salty piece of bacon.",
        "What is AI? Briefly explain its role in art generation processes.",
        "Write a short, inspiring sentence about the power of dreams.",
        "Explain the difference between 'debt' and 'equity' in finance.",
        "List three common types of grains used in breakfast foods.",
        "Describe the feeling of softness of a warm, fluffy blanket.",
        "What is the Big Bang theory? Explain its implications for cosmic expansion.",
        "Imagine a robot designed for creative writing and storytelling.",
        "Explain the concept of 'confirmation bias' in scientific fields.",
        "List three benefits of daily gratitude journaling for well-being.",
        "Describe the sound of wind whispering through dry grass fields.",
        "What is gravity? Briefly explain its role in stellar formation.",
        "Write a short, whimsical sentence about a talking broom.",
        "Explain the difference between 'weather' and 'climate' in academic terms.",
        "List three common types of reptiles found in rainforests.",
        "Describe the smell of fresh pine needles on a forest floor.",
        "What is photosynthesis? Explain its process in detail, simply.",
        "Imagine a plant that can change its form at will.",
        "Explain the 'Pareto principle' in customer service and satisfaction.",
        "List three benefits of spending time in nature for mental clarity.",
        "Describe the sound of gentle waves lapping on a quiet lake shore.",
        "What is the Internet of Things? Explain its impact on manufacturing.",
        "Write a short, inspiring sentence about collective human effort.",
        "Explain the difference between 'ethical' and 'moral' choices in society.",
        "List three common types of birds that sing beautiful melodies.",
        "Describe the taste of warm, creamy tomato soup.",
        "What is a black hole? Briefly explain its event horizon and gravity.",
        "Imagine a pet robot that helps with personal health monitoring.",
        "Explain the concept of 'cognitive dissonance' in consumer decisions.",
        "List three major mountain ranges in South America.",
        "Describe the sound of a distant, peaceful melody.",
        "What is a neuron? Explain its role in learning new things.",
        "Write a short, optimistic sentence about future possibilities.",
        "Explain the difference between 'efficiency' and 'effectiveness' in work.",
        "List three common ingredients in a homemade pizza sauce.",
        "Describe the feeling of joy when reunited with loved ones.",
        "What is DNA? Explain its role in personalized medicine.",
        "Imagine a world where animals have their own social networks.",
        "Explain the 'halo effect' in job interviews, providing examples.",
        "List three major historical figures from the Renaissance.",
        "Describe the sound of gentle rain on a canvas tent, softly.",
        "What is climate change? List its impact on global temperatures.",
        "Write a short, funny sentence about a robot trying to cook.",
        "Explain the difference between 'Wi-Fi' and 'Ethernet.'",
        "List three common types of mammals in your local area.",
        "Describe the smell of warm, freshly baked cookies from a nearby kitchen.",
        "What is a satellite? Briefly explain its use in disaster management.",
        "Imagine a device that lets you explore different dimensions.",
        "Explain the 'bystander effect' in online communities, with greater detail.",
        "List three benefits of learning basic first aid skills.",
        "Describe the taste of a crispy, fresh apple.",
        "What is AI? Briefly explain its role in personal assistants.",
        "Write a short, inspiring sentence about the human spirit.",
    ]


if __name__ == "__main__":
    main()
